#!/usr/bin/bash

wget ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate/hourly/wind/historical/stundenwerte_FF_01346_19550101_20151231_hist.zip

wget http://www.syscop.de/files/2016ws/msi/exercises/exercise6.pdf
