function [wind_data] = import_data(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [MESS_DATUM,WINDGESCHWINDIGKEIT] = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   [MESS_DATUM,WINDGESCHWINDIGKEIT] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [MESS_DATUM,WINDGESCHWINDIGKEIT] = importfile('produkt_wind_Terminwerte_19550101_20151231_01346.txt',2, 409715);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/12/06 11:41:22

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column2: double (%f)
%	column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f%*s%*s%f%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
MESS_DATUM = dataArray{:, 1};
WINDGESCHWINDIGKEIT = dataArray{:, 2};


wind_data = WINDGESCHWINDIGKEIT(round(MESS_DATUM/1e6) == 2015)